### ISSUE TITLE
Work on debug version, but not work for release version

### ISSUE THREAD

**Issue by jezhang2014** [brahma-adshonor/gohook#27]
I used go 1.13.5 version on both windows and linux with github.com/brahma-adshonor/gohook v0.0.0-20191009123657-4dfde2738c74, and run sample. it seems only work as expected on debug mode, not work on release mode.

**Comment by kmalloc** [comment]
@jezhang2014 debug mode 是什么意思？出错信息是什么？怎么复现？
btw，编译例子的时候需要禁掉 inline

**Comment by liov** [comment]
我估计是fmt.Println在release模式下会被内联，然而-cflags '-l' 不如用动态语言更自由
