### ISSUE TITLE
能否实现hook其它包下的普通函数呢？

### ISSUE THREAD

**Issue by 0xlwoe21k** [brahma-adshonor/gohook#41]
比如：如何在package main里hook  A包里的test() 函数呢？

**Comment by kmalloc** [comment]
readme 里面的例子和你的场景是一模一样的

**Comment by 0xlwoe21k** [comment]
readme里hook的是导出函数，这里我可能没描述清楚，我这里是要hook其它包里的非导出函数

**Comment by kmalloc** [comment]
这个目前不支持，而且在我看来没必要，非导出函数属于内部行为，变动的可能性太高了，如果非要拦截，可以参考一下下面的工具：https://github.com/alangpierce/go-forceexport

**Comment by 0xlwoe21k** [comment]
好的，感谢。
