### ISSUE TITLE
HookMethod不生效

### ISSUE THREAD

**Issue by hxupup** [brahma-adshonor/gohook#54]
Linux：uname -a
Linux n37-050-162 5.4.143.bsk.8-amd64 #5.4.143.bsk.8 SMP Debian 5.4.143.bsk.8 Wed Jul 20 08:43:36 UTC  x86_64 GNU/Linux
go version go1.19.12 linux/amd64

example/main.go 中 HookMethod Buffer.Len，在我的环境中不生效。

我打印了target函数HookMethod前后的变化：
HookMethod之前：
instruction:  MOV RCX, [RAX+0x8]
instruction:  SUB RCX, [RAX+0x18]
instruction:  MOV RAX, RCX
instruction:  RET

HookMethod之后：
instruction:  JMP .+505883
instruction:  SUB ECX, [RAX+0x18]
instruction:  MOV RAX, RCX
instruction:  RET

看着确实把JMP写进去了，但是并没有生效。后面调用Len依然是返回的4，而不是233

然而example/main.go 中TestAsm是生效的，看着也是写入了JMP指令：
Hook前：
instruction:  CMP RSP, [R14+0x10]
instruction:  JBE .+159
instruction:  SUB RSP, 0x60
instruction:  MOV [RSP+Reg(0)+0x58], RBP
instruction:  LEA RBP, [RSP+Reg(0)+0x58]
instruction:  MOV [RSP+Reg(0)+0x70], RBX
instruction:  MOV [RSP+Reg(0)+0x78], RCX
instruction:  MOV [RSP+Reg(0)+0x68], RAX
instruction:  MOVUPS [RSP+Reg(0)+0x38], X15
instruction:  MOVUPS [RSP+Reg(0)+0x48], X15
instruction:  CALL .-948248
instruction:  LEA RCX, [RIP+0xd741]
instruction:  MOV [RSP+Reg(0)+0x38], RCX
instruction:  MOV [RSP+Reg(0)+0x40], RAX
instruction:  MOV RAX, [RSP+Reg(0)+0x70]
instruction:  MOV RBX, [RSP+Reg(0)+0x78]
instruction:  CALL .-948152
instruction:  LEA RCX, [RIP+0xde61]
instruction:  MOV [RSP+Reg(0)+0x48], RCX
instruction:  MOV [RSP+Reg(0)+0x50], RAX
instruction:  MOV RBX, [RIP+0x124e78]
instruction:  LEA RAX, [RIP+0x60321]
instruction:  LEA RCX, [RIP+0x2f82e]
instruction:  MOV EDI, 0xc
instruction:  LEA RSI, [RSP+Reg(0)+0x38]
instruction:  MOV R8L, 0x2
instruction:  MOV R9, R8
instruction:  CALL .-177014
instruction:  MOV RAX, [RSP+Reg(0)+0x68]
instruction:  ADD RAX, 0x2a
instruction:  MOV RBP, [RSP+Reg(0)+0x58]
instruction:  ADD RSP, 0x60
instruction:  RET
instruction:  MOV [RSP+Reg(0)+0x8], RAX
instruction:  MOV [RSP+Reg(0)+0x10], RBX
instruction:  MOV [RSP+Reg(0)+0x18], RCX
instruction:  CALL .-568029
instruction:  MOV RAX, [RSP+Reg(0)+0x8]
instruction:  MOV RBX, [RSP+Reg(0)+0x10]
instruction:  MOV RCX, [RSP+Reg(0)+0x18]
instruction:  JMP .-209

Hook后：
instruction:  JMP .+219
instruction:  XCHG BH, BL

**Comment by kmalloc** [comment]
应该是 inline 了 编译的时候把优化关一下
